Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder "scripts", "/home/vagrant/scripts"
  config.vm.synced_folder "webapps/", "/home/vagrant/webapps"
  #config.vm.synced_folder "depl-app/", "/home/vagrant/depl-app"
  config.vm.synced_folder "dump/", "/tmp/dump"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    sudo -i
    cd /home/vagrant/scripts
    sudo apt install dos2unix
    dos2unix .env
    dos2unix bootstrap.sh
    dos2unix /home/vagrant/webapps/config/setenv.sh
    /home/vagrant/scripts/bootstrap.sh
  SHELL
  config.vm.network "private_network", ip: "192.168.56.20"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.cpus = "2"
   end
end