# Tables: Tables are collections of key/value pairs that are defined by headers on a new line surrounded by square brackets ([]). The table ends when a new header is provided or when the file ends.
[database]
url = "mongodb://localhost:27017"
name = "mydb"
username = "myuser"
password = "mypassword"
level = "info"

# Integers/Floats
integer = 20
float = 20.5

#Arrays: Arrays are surrounded by square brackets with elements separated by commas (,).
colors = [ "red", "yellow", "green" ]

["button/delete"]
  defaultPassword = "削除 を削除PP"

["vert"]
  password = "はい、すべてを削除します"