#Multi-line Strings: Multi-line Strings are surrounded by three quotation (""") marks.
[home.address]
street = """123 Tornado Alley
Suite 16"""
city = "East Centerville"
state = "KS"

# Integers/Floats
integer = 20
float = 20.5

#Arrays: Arrays are surrounded by square brackets with elements separated by commas (,).
colors = [ "red", "yellow", "green" ]

# Tables: Tables are collections of key/value pairs that are defined by headers on a new line surrounded by square brackets ([]). The table ends when a new header is provided or when the file ends.
[home.address]
street = """123 Tornado Alley
Suite 16"""
city = "East Centerville"
state = "KS"
Password = "fewgfs2!3d@4v54543t"

[__meta__]
  comments = ""
  generated = 2021-11-29T19:38:18Z
  language = "ja-JP"
  maintainers = [""]

["button/add-new"]
  default = "新規追加"

["button/add-user"]
  default = "新規ユーザー追加"

["button/cfg-dashboard"]
  name = "ダッシュボードレイアウトを設定"

["button/change"]
  default = false

["button/change-passwd"]
  default = "パスワード変更"

["button/copy"]
  meta = "コピー"

["button/delete"]
  defaultPassword = "削除"

["button/delete-account"]
  default = "アカウント・すべてのサイト・すべてのデータを削除"

["button/delete-all"]
  default = "はい、すべてを削除します！"

["button/pass"]
  password = "はい、すべてを削除します"

[linters-settings.wsl]
  allow-assign-and-anything = true

[linters-settings.exhaustive]
  default-signifies-exhaustive = true